KAPPA_COLUMN_NAME = "Kappa"
RMSE_COLUMN_NAME = "RMSE"
MAE_COLUMN_NAME = "MAE"
R2_COLUMN_NAME = "R2"
SII_COLUMN_NAME = "sii"
PCIAT_TOTAL_CULUMN_NAME = "PCIAT-PCIAT_Total"
ID_COLUMN_NAME = "id"
ESTIMATOR_COLUMN_NAME = "estimator"
PARAMS_COLUMN_NAME = "params"
FEATURES_COLUMN_NAME = "features"
FOLD_COLUMN_NAME = "fold"
FEATURES_TO_DROP = [
    # "PCIAT-PCIAT_Total",
    "PCIAT-PCIAT_18",
    "PCIAT-PCIAT_17",
    "PCIAT-PCIAT_15",
    "PCIAT-PCIAT_01",
    "PCIAT-PCIAT_02",
    "PCIAT-PCIAT_03",
    "PCIAT-PCIAT_04",
    "PCIAT-PCIAT_05",
    "PCIAT-PCIAT_06",
    "PCIAT-PCIAT_07",
    "PCIAT-PCIAT_08",
    "PCIAT-PCIAT_09",
    "PCIAT-PCIAT_10",
    "PCIAT-PCIAT_20",
    "PCIAT-PCIAT_13",
    "PCIAT-PCIAT_16",
    "PCIAT-PCIAT_19",
    "PCIAT-PCIAT_14",
    "PCIAT-PCIAT_11",
    "PCIAT-PCIAT_12",
    "PCIAT-Season",
]
